import os
import json
import re
from groq import Groq

_SYSTEM_PROMPT = """\
You are an AI-content detection assistant. Given a passage of text, assess whether it was \
written by a human or generated by an AI language model.

Respond ONLY with a JSON object — no markdown, no explanation outside the JSON. \
The object must have exactly these fields:
  "classification": one of "ai", "human", or "uncertain"
  "confidence": a float between 0.0 and 1.0 representing how likely the text is AI-generated \
(1.0 = certainly AI, 0.0 = certainly human)
  "reasoning": a short string (1–3 sentences) explaining the key signals you detected

Example response:
{"classification":"ai","confidence":0.91,"reasoning":"The text uses uniform sentence lengths and formal hedging language typical of AI output."}
"""


def analyze(text: str) -> dict:
    """
    Calls Groq (llama-3.3-70b-versatile) to estimate AI-generation likelihood.
    Returns {"score": float, "reasoning": str, "classification": str}.
    Falls back to {"score": 0.5, ...} on any failure.
    """
    try:
        client = Groq(api_key=os.environ["GROQ_API_KEY"])
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": f"Passage:\n\n{text}"},
            ],
            temperature=0.0,
            max_tokens=256,
        )
        raw = response.choices[0].message.content.strip()

        # Strip markdown code fences if the model wraps the JSON
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw)

        parsed = json.loads(raw)
        cls = parsed.get("classification", "uncertain")
        certainty = max(0.0, min(1.0, float(parsed["confidence"])))

        # The model returns "confidence in its classification", not P(AI).
        # Convert to AI-likelihood score our pipeline expects (1.0 = certainly AI).
        if cls == "ai":
            score = certainty
        elif cls == "human":
            score = 1.0 - certainty
        else:
            score = 0.5

        return {
            "score": round(score, 4),
            "classification": cls,
            "reasoning": parsed.get("reasoning", ""),
        }
    except Exception as exc:
        return {
            "score": 0.5,
            "classification": "uncertain",
            "reasoning": f"LLM signal unavailable: {exc}",
        }
